Should have fixed the fact that you couldn't supply more than one long argument at once from the first case statement.

diff --git a/bmpc b/bmpc
--- a/bmpc
+++ b/bmpc
@@ -90,44 +90,48 @@ function displayHelp() {
 }
 
 # Code
-
-case "$1" in
-	'--host')
-		if [ ! "$3" ]; then
-			echo -e "  ${c5} ERROR!${c0}  You did not supply a host and/or a command."
-			exit 1
-		else
-			MPD_HOST="$2"
-			shift 2
-		fi
-	;;
-	'--port')
-		if [ ! "$3" ]; then
-			echo -e "  ${c5} ERROR!${c0}  You did not supply a port and/or a command."
-			exit 1
-		else
-			MPD_PORT="$2"
-			shift 2
-		fi
-	;;
-	'--pass')
-		if [ ! "$3" ]; then
-			echo -e "  ${c5} ERROR!${c0}  You did not supply a pass and/or a command."
-			exit 1
-		else
-			MPD_PASS="$2"
-			shift 2
-		fi
-	;;
-	'--nocolor')
-		c1=${c0}
-		c2=${c0}
-		c3=${c0}
-		c4=${c0}
-		c5=${c0}
-		shift
-	;;
-esac
+while [[ $# -gt 1 ]]; do
+	case "$1" in
+		'--host')
+			if [ ! "$3" ]; then
+				echo -e "  ${c5} ERROR!${c0}  You did not supply a host and/or a command."
+				exit 1
+			else
+				MPD_HOST="$2"
+				shift 2
+			fi
+		;;
+		'--port')
+			if [ ! "$3" ]; then
+				echo -e "  ${c5} ERROR!${c0}  You did not supply a port and/or a command."
+				exit 1
+			else
+				MPD_PORT="$2"
+				shift 2
+			fi
+		;;
+		'--pass')
+			if [ ! "$3" ]; then
+				echo -e "  ${c5} ERROR!${c0}  You did not supply a pass and/or a command."
+				exit 1
+			else
+				MPD_PASS="$2"
+				shift 2
+			fi
+		;;
+		'--nocolor')
+			c1=${c0}
+			c2=${c0}
+			c3=${c0}
+			c4=${c0}
+			c5=${c0}
+			shift
+		;;
+		*)
+			break 1
+		;;
+	esac
+done
 
 # MPD server settings
 
